#!/bin/bash
#
# Copyright (c) 2017 The Absolute Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

. $ABSOLUTE_PATH/bootstrap/common/path_info.sh

echo "Available commands:"
for command in $(ls $(bootstrap_command_path)); do
  echo "    absolute $command"
done
