#!/bin/bash
#
# Copyright (c) 2017 The Absolute Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

. bootstrap/common/path_info.sh

trap "cd - > /dev/null" EXIT
cd $(server_path) && npm install . && stop && forever start ./server.js
