#!/bin/bash
#
# Copyright (c) 2017 The Absolute Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

export ABSOLUTE_PATH=$(cd $(dirname $BASH_SOURCE); pwd)
cd $ABSOLUTE_PATH && source ./bootstrap/absolute.sh "from-sh" $@;
