#!/bin/bash

source ./scripts/path_info
source ./scripts/util

NODEJS_WIN_x64="win-x64"
NODEJS_WIN_x86="win-x86"
NODEJS_LINUX_x64="linux-x64"
NODEJS_LINUX_x86="linux-x86"
NODEJS_MAC_x64="darwin-x64"
# TODO : This is temporal fixed version. Need to get latest or specific version from dist repository
NODEJS_VERSION="v6.9.5"
NODEJS_7x_LATEST_URL="https://nodejs.org/dist/$NODEJS_VERSION/"
NODEJS_VERSION_NAME="node-$NODEJS_VERSION"

# Get the nodeJS binary for running platform
# $1 : platform name
function get_nodejs_binary() {
  platform_name=$1
  if [ "$platform_name" = "linux_x86_64" ]; then
    target_node_platform_name="$NODEJS_VERSION_NAME-$NODEJS_LINUX_x64"
    target_node_archive_file="$target_node_platform_name.tar.gz"
  elif [ "$platform_name" = "linux_x86" ]; then
    target_node_platform_name="$NODEJS_VERSION_NAME-$NODEJS_LINUX_x86"
    target_node_archive_file="$target_node_platform_name.tar.gz"
  elif [ "$platform_name" = "windows_x86_64" ]; then
    target_node_platform_name="$NODEJS_VERSION_NAME-$NODEJS_WIN_x64"
    target_node_archive_file="$target_node_platform_name.zip"
  elif [ "$platform_name" = "windows_x86" ]; then
    target_node_platform_name="$NODEJS_VERSION_NAME-$NODEJS_WIN_x86"
    target_node_archive_file="$target_node_platform_name.zip"
  elif [ "$platform_name" = "darwin_x86_64" ]; then
    target_node_platform_name="$NODEJS_VERSION_NAME-$NODEJS_MAC_x64"
    target_node_archive_file="$target_node_platform_name.tar.gz"
  fi

  target_url="$NODEJS_7x_LATEST_URL/$target_node_archive_file"

  target_node_dir=$(get_node_dir)

  download_file_to_path "$target_url" "$target_node_dir"
  if [ ! "$?" = "0" ]; then
    return
  fi

  extract_archive "$target_node_dir/$target_node_archive_file" \
  "$target_node_dir"; rm -f $target_node_dir/$target_node_archive_file

  # FIXME(Jaecule) : This workaround is for removing dir
  # of archive file need more graceful way
  mv $target_node_dir/$target_node_platform_name/* "$target_node_dir/"
  rmdir "$target_node_dir/$target_node_platform_name"
}

# Get the download file to given path
# $1 : download url
# $2 : file to locate
# Out: 0 if success to download file else negative
function download_file_to_path() {
  url=$1
  path=$2
  if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Invalid download url or path url : $1 path : $2"
    return -1
  fi

  echo "download from $url to $path"

  if [ ! -d "$path" ]; then
    echo "targetPath does not exist. create $path"
    mkdir $path
  fi

  download_file $url $path
  if [ "$?" != "0" ]; then
    echo "Failed to download"
    return -2
  fi

  return 0
}

# extract archive files to given path
#
# Arguments:
# $1 : path of archive
# $2 : path of uncompressed files
# Remarks : if $2 is not given, uncompress files to current path
function extract_archive() {
  if [ -z "$2" ]; then
    dest="./"
  else
    dest="$2"
  fi

  if [ -f "$1" ] ; then
    case $1 in
      *.tar.gz) tar xvzf $1 -C $dest ;;
      *.gz) gunzip $1 > $dest ;;
      *.tar) tar xvf $1 -C $dest ;;
      # FIXME(Jaechul): Current our win-bash doens't support unzip!
      # So this woudn't run on windows
      *.zip) third_party/win-unzip/bin/unzip $1 -d $dest ;;
      *.7z) 7z x $1 -o $dest ;;
      *) echo "extract: '$1' - unknown archive method" ;;
    esac
  else
    echo "$1 - file does not exist"
  fi
}
