#!/bin/bash

# This file is providing some APIs to get absolute path information.

source ./scripts/platform_info

function get_script_dir() {
  echo $(get_absolute_dir)/script
}

function get_absolute_dir() {
  echo $(cd $(dirname $0)/..; pwd -P)
}

function get_node_dir() {
  echo $(get_absolute_dir)/platform/nodejs
}

function get_mongodb_dir() {
  echo $(get_absolute_dir)/platform/mongodb
}

function get_server_dir() {
  echo $(get_absolute_dir)/server
}

function get_win_bash_dir() {
  echo $(get_absolute_dir)/third_party/win-bash
}

function get_win_unzip_dir() {
  echo $(get_absolute_dir)/third_party/win-unzip/bin
}
