#!/bin/bash

# This file is providing some APIs to retrive platform information.

source ./scripts/string_util

# Get the platform name on current system.
# Out: The name of the platform that invokes this function.
get_platform_name() {
  # If the OS system is MS windows, then we can check a processor type via
  # the following environment variables:
  #   $PROCESSOR_ARCHITECTURE: Reports the native processor architecture
  #                            EXCEPT for WOW64, where it reports x86.
  #   $PROCESSOR_ARCHITEW6432: Not used EXCEPT for WOW64, where it reports
  #                            the original native processor architecture.
  #
  # Please see the following link in details:
  #   https://blogs.msdn.microsoft.com/david.wang/2006/03/27/howto-detect-process-bitness/
  if [ "$(to_lower $PROCESSOR_ARCHITEW6432)" = "amd64" \
      -o "$(to_lower $PROCESSOR_ARCHITECTURE)" = "amd64" ]; then
    # FIXME(zino): Once we finish to implement NodeJS Downloader via script,
    # the following platform name should be |windows_x86_64|.
    # Please see: https://github.com/romandev/absolute/issues/19
    echo "node-v7.3.0-win-x64"
    return
  fi

  os_name=$(to_lower $(uname -s))
  if [ "$os_name" = "windows_nt" ]; then
    # FIXME(zino): Once we finish to implement NodeJS Downloader via script,
    # the following platform name should be |windows_x86_64|.
    # Please see: https://github.com/romandev/absolute/issues/19
    echo "node-v7.3.0-win-x86"
    return
  fi

  echo $os_name"_"$(uname -m)
}
