#!/bin/bash

source ./scripts/get_nodejs_bin
source ./scripts/get_mongodb_bin
source ./scripts/path_info
source ./scripts/platform_info

function run_server() {
  platform_name=$(get_platform_name)

  # FIXME(zino): Once we finish to implement NodeJS Downloader via script,
  # the following platform name should be |windows_x86_64| or |windows_x86|.
  # Please see: https://github.com/romandev/absolute/issues/19
  if $(is_windows); then
    $(get_node_dir)/npm.cmd install $(get_server_dir) --prefix $(get_server_dir)
    $(get_node_dir)/npm.cmd start --prefix $(get_server_dir)
  else
    $(get_node_dir)/bin/npm install $(get_server_dir) --prefix $(get_server_dir)
    $(get_node_dir)/bin/npm start --prefix $(get_server_dir)
  fi
}

function set_path_configuration() {
  platform_name=$(get_platform_name)
  if $(is_windows); then
    export PATH=$PATH:$(get_win_bash_dir):$(get_win_unzip_dir):$(get_mongodb_dir)/bin
  else
    PATH=$PATH:$(get_node_dir)/bin
  fi
}

set_path_configuration

if [ ! -d $(get_node_dir) ]; then
  get_nodejs_binary $(get_platform_name)
fi

if [ ! -d $(get_mongodb_dir) ]; then
  get_mongodb_binary $(get_platform_name)
fi

run_server
