#!/bin/bash

source ./scripts/get_nodejs_bin
source ./scripts/path_info
source ./scripts/platform_info

function run_server() {
  platform_name=$(get_platform_name)

  # FIXME(zino): Once we finish to implement NodeJS Downloader via script,
  # the following platform name should be |windows_x86_64| or |windows_x86|.
  # Please see: https://github.com/romandev/absolute/issues/19
  if [ "$platform_name" = "node-v7.3.0-win-x64" \
      -o "$platform_name" = "node-v7.3.0-win-x86" ]; then
    $(get_node_dir)/npm.cmd install $(get_server_dir) --prefix $(get_server_dir)
    $(get_node_dir)/npm.cmd start --prefix $(get_server_dir)
  else
    PATH=$PATH:$(get_node_dir)/bin
    $(get_node_dir)/bin/npm install $(get_server_dir) --prefix $(get_server_dir)
    $(get_node_dir)/bin/npm start --prefix $(get_server_dir)
  fi
}

if [ ! -d $(get_node_dir) ]; then
  get_nodejs_binary $(get_platform_name)
fi

run_server
