#!/bin/bash
source ./scripts/path_info
source ./scripts/util

function run_gulp() {
  platform_name=$(get_platform_name)
  
  if $(is_windows); then
    #TODO(gitdongguri): run gulp in windows
    echo "ttt"
  else
  echo "eeee"
    PATH=$PATH:$(get_node_dir)/bin
    node_module_bin_dir=$(npm bin --prefix $(get_server_dir))
    #FIXME(gitdongguri): have to use command in package.json
    node $node_module_bin_dir/gulp --gulpfile $(get_server_dir)/gulpfile.js &
  fi
}

run_gulp
